config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :answers
  resources :questions
  get 'comments/create'

  get 'comments/destroy'

  root 'welcome#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :bulletins do
  resources :posts
end

  

end

app/models/bulletin.rb
class Bulletin < ActiveRecord::Base
	has_many :posts, dependent: :destroy
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  before_action :set_bulletin, only: [:show, :edit, :update, :destroy]

  # GET /bulletins
  # GET /bulletins.json
  def index
    @bulletins = Bulletin.all
  end

  # GET /bulletins/1
  # GET /bulletins/1.json
  def show
  end

  # GET /bulletins/new
  def new
    @bulletin = Bulletin.new
  end

  # GET /bulletins/1/edit
  def edit
  end

  # POST /bulletins
  # POST /bulletins.json
  def create
    @bulletin = Bulletin.new(bulletin_params)

    respond_to do |format|
      if @bulletin.save
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully created.' }
        format.json { render :show, status: :created, location: @bulletin }
      else
        format.html { render :new }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulletins/1
  # PATCH/PUT /bulletins/1.json
  def update
    respond_to do |format|
      if @bulletin.update(bulletin_params)
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulletin }
      else
        format.html { render :edit }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulletins/1
  # DELETE /bulletins/1.json
  def destroy
    @bulletin.destroy
    respond_to do |format|
      format.html { redirect_to bulletins_url, notice: 'Bulletin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :post_type)
    end
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/views/bulletins/_form.html.erb
<%= simple_form_for(@bulletin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, input_html: { rows: 10 } %>
    <%= f.input :post_type, collection: [ ['게시판', 'bulletin'], ['블로그', 'blog'], ['갤러리', 'gallery'] ] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bulletins/edit.html.erb
<h2>공지 수정</h2>

<%= render 'form' %>

<hr>

<%= link_to 'Show', @bulletin, class: 'btn btn-default' %>
<%= link_to 'Back', bulletins_path, class: 'btn btn-default' %>

app/views/bulletins/index.html.erb
<h2>Bulletins</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Data actions</th>
    </tr>
  </thead>

  <tbody>
    <% @bulletins.each do |bulletin| %>
      <tr>
        <td><%= bulletin.title %></td>
        <td><%= bulletin.description %></td>
        <td>
          <%= link_to 'Show', bulletin, class: 'btn btn-info' %>
          <%= link_to 'Edit', edit_bulletin_path(bulletin), class: 'btn btn-default' %>
          <%= link_to 'Destroy', bulletin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bulletin', new_bulletin_path, class: 'btn btn-default' %>

app/views/bulletins/new.html.erb
<h1>New Bulletin</h1>

<%= render 'form' %>

<hr>

<%= link_to 'Back', bulletins_path, class: 'btn btn-default' %>

app/views/bulletins/show.html.erb
<h2>여기 보세요.</h2>

<table class='table table-bordered'>
<tr>
  <th>공지</th>
  <td><%= @bulletin.title %></td>
</tr>
<tr>
  <th>내용</th>
  <td><%= @bulletin.description %></td>
</tr>
<tr>
<tr>
  <th>속성</th>
  <td><%= @bulletin.post_type %></td>
</tr>
  <th>작성일시</th>
  <td><%= @bulletin.created_at %></td>
</tr>
</table>

<%= link_to 'Edit', edit_bulletin_path(@bulletin), class: 'btn btn-default' %>
<%= link_to 'Back', bulletins_path, class: 'btn btn-default' %>