config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :answers
  resources :questions
  get 'comments/create'

  get 'comments/destroy'

  root 'welcome#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :bulletins do
  resources :posts
end

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	validates :content, presence: true
 	belongs_to :question
 	belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @question = @answer.question

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render 'questions/show' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @question = @answer.question
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content, :question_id, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= simple_form_for(@answer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.hidden_field :question_id %>
    <%= f.hidden_field :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.content %></td>
        <td><%= answer.question %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answssssser</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>