config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :answers
  resources :questions
  get 'comments/create'

  get 'comments/destroy'

  root 'welcome#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :bulletins do
  resources :posts
end

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :bulletin
	mount_uploader :picture, PictureUploader
	has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_bulletin
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = @bulletin.posts.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @bulletin.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @bulletin.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@post.bulletin, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [@post.bulletin, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to bulletin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bulletin
      @bulletin = Bulletin.find(params[:bulletin_id])
    end

    def set_post
      @post = @bulletin.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :picture, :picture_cache)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

	def bulletin_name(bulletin_id)
    Bulletin.find(bulletin_id).title
  end

end

app/views/posts/post_types/_blog.html.erb
<h2><%= bulletin_name params[:bulletin_id] %> <small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id])%></small></h2>

<% @posts.each do | post | %>
    <div class='post'>
      <div class='title'><%= post.title %></div>
      <div class='content'><%= simple_format post.content %></div>
      <div>
          <%= link_to 'Show', [post.bulletin, post], class:'btn btn-default' %>
          <%= link_to 'Edit', edit_bulletin_post_path(post.bulletin, post), class:'btn btn-default' %>
          <%= link_to 'Destroy', [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default' %>
      </div>
    </div>
<% end %>

<br>

<%= link_to 'New Post', new_bulletin_post_path, class: 'btn btn-default' %>

app/views/posts/post_types/_bulletin.html.erb
<h2><%= bulletin_name params[:bulletin_id] %> <small><%= link_to '설정', edit_bulletin_path(params[:bulletin_id])%></small></h2>


<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Data actions</th>
    </tr>
  </thead>

  <tbody>
<% @posts.each do |post| %>
  <tr>
     <td><%= post.title %> <small>( <%= post.comments.size %> )</small></td> 
      <%= link_to 'Show', [post.bulletin, post], class:'btn btn-default' %>
      <%= link_to 'Edit', edit_bulletin_post_path(post.bulletin, post), class:'btn btn-default' %>
      <%= link_to 'Destroy', [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default' %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>


<%= link_to 'New Post', new_bulletin_post_path, class: 'btn btn-default' %>

app/views/posts/post_types/_gallery.html.erb
<h2><%= bulletin_name params[:bulletin_id] %></h2>

<div class='gallery'>
<% @posts.each do | post | %>
    <div class='col-lg-3 col-md-3 col-xs-4  picture'>
      <div class='image'><%= link_to(image_tag(post.picture_url(:thumb)), [post.bulletin, post]) if post.picture? %></div>
      <div class='title'><%= post.title %></div>
      <div class='content'><%= post.content %></div>
      <div class='actions'>
          <%= link_to fa_icon('eye'), [post.bulletin, post] %>
          <%= link_to fa_icon('edit'), edit_bulletin_post_path(post.bulletin, post) %>
          <%= link_to fa_icon('trash'), [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
<% end %>
</div>
<br>

<%= link_to 'New Post', new_bulletin_post_path, class: 'btn btn-default' %>